### ISSUE TITLE
Result not shown in browser

### ISSUE THREAD

**Issue by r3curs1v3-pr0xy** [0xdekster/ReconNote#2]
Hi

Thanks for creating this framework!
But today when I tried to test this framework, I didn't got any result of the scan. Neither of the scan is working. Everything goes fine while installing.
Can you look at this?

**Comment by end1an** [comment]
@r3curs1v3-pr0xy 
Which port do you using? If you change the port you should edit a PORT in the docker file too.
You can debug the error information from the dev console when you click scan.

**Comment by 0xdekster** [comment]
Hi @r3curs1v3-pr0xy Can you brief whats the issue and error you are encountering by providing any log or error messages ?

**Comment by sabeesh03** [comment]
hi prasoon 
even i faced the same error I didn't got any result of the scan. Neither of the scan is working. Everything goes fine while installing. port used is 3000 

NO ERROR is generated

**Comment by pranav-byte** [comment]
Same issue faced @0xdekster.Port used is 3000

**Comment by sabeesh03** [comment]
out path configured , apache installed 
however no result found

**Comment by 0xdekster** [comment]
@sabeesh03  @pranav-byte The issue might be in your output path and do install apache.

**Comment by end1an** [comment]
I think the issue is output path doesn't have the scan results from the tools.
I created a container with this docker-compose.yml
`version: "3.1"

services:
 dekster:
    ulimits:
          nofile:
              soft: 65536
              hard: 65536
    build: .
    ports:
      - 9000:9000
    volumes:
      - ../scans-output/:/var/www/html/recon/
    environment:
      - SCANS_OUTPUT_DIR_PATH=/var/www/html/recon/
      - API_HOST=188.166.212.132
      - NUXT_PORT=9000`

The result is no any scan result in the ReconNote.
The problem is tools will generate the result to path /var/www/html/ but the volume was mapping to /var/www/html/recon/
